<?php

/**
 * Class-SelectLocationOnRegister.php
 *
 * @package SelectLocationOnRegister
 * @link https://github.com/Rumpa20/select-location-on-register
 * @author Rumpa
 * @copyright 2024 Rumpa
 * @license https://opensource.org/licenses/BSD-3-Clause The 3-Clause BSD License
 *
 * @version 1.0
 */

namespace Rumpa;

/**
 * Generated by SimpleModMaker
 */
class SelectLocationOnRegister
{
	public function hooks()
	{
		add_integration_function('integrate_load_custom_profile_fields', __CLASS__ . '::loadCustomProfileFields#', false, __FILE__);
		add_integration_function('integrate_register', __CLASS__ . '::register#', false, __FILE__);
	}

	/**
	 * @hook integrate_load_custom_profile_fields
	 */
	public function loadCustomProfileFields()
	{
		global $context, $location, $txt;

		if (empty($context['location']) || in_array($context['current_action'], array('admin', 'signup')) === false)
			return;

		loadLocation('Profile');

		$html = '';
		foreach ($context['location'] as $loc => $data) {
			$html .= '<option value="' . $loc . '"' . ($location == $loc ? ' selected' : '') . '>' . $data['name'] . '</option>';
		}

		$context['custom_fields'][] = array(
			'name' => $txt['location'],
			'desc' => $txt['preferred_location'],
			'input_html' => '<select name="location" id="location">' . $html . '</select>',
			'show_reg' => '2'
		);

		$context['custom_fields_required'] = true;
	}

	/**
	 * @hook integrate_register
	 */
	public function register(&$regOptions)
	{
		$regOptions['register_vars']['locfile'] = isset($_POST['location']) ? $_POST['location'] : '';
	}
}
